apiVersion: portfolio/v1
kind: Project
metadata:
  name: portfolio-rs
  namespace: fabien-cayre
spec:
  template:
    spec:
      restartPolicy: Never
      source: https://github.com/Fabccc/portfolio
      type: personal-project
      maxReplicas: 1
      stack:
        - name: frontend
          type: spa
          framework: leptos 
          language: rust
          why: Why not
      ports:
        - containerPort: "80"
          name: "http"
---
kind: Ingress
metadata:
  name: portfolio-rs
  namespace: fabien-cayre
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - www.fabiencayre.fr
      secretName: certbot-fabiencayre
  rules:
    - http:
      - path: /
        pathType: Prefix
        backend:
           service:
             name: portfolio-rs
             port:
               name: http